final List<Map<String, String>> doctors = [
  {
    "image": "assets/images/male-doctor.png",
    "name": "Dr. Marcus Horizon",
    "specialty": "Cardiologist",
    "rating": "4.7",
    "distance": "800m Away",
  },
  {
    "image": "assets/images/docto3.png",
    "name": "Dr. Maria Elena",
    "specialty": "Psychologist",
    "rating": "4.6",
    "distance": "1.2km Away",
  },
  {
    "image": "assets/images/doctor2.png",
    "name": "Dr. Stevi Jessi",
    "specialty": "Orthopedist",
    "rating": "4.8",
    "distance": "2km Away",
  },
  {
    "image": "assets/images/black-doctor.png",
    "name": "Dr. James Carter",
    "specialty": "Neurologist",
    "rating": "4.9",
    "distance": "1.5km Away",
  },
  {
    "image": "assets/images/male-doctor.png",
    "name": "Dr. Sarah Kim",
    "specialty": "Pediatrician",
    "rating": "4.5",
    "distance": "900m Away",
  },
  {
    "image": "assets/images/docto3.png",
    "name": "Dr. Ahmed Ali",
    "specialty": "Dermatologist",
    "rating": "4.7",
    "distance": "1.1km Away",
  },
  {
    "image": "assets/images/doctor2.png",
    "name": "Dr. Lisa Wong",
    "specialty": "Gynecologist",
    "rating": "4.8",
    "distance": "2.3km Away",
  },
  {
    "image": "assets/images/black-doctor.png",
    "name": "Dr. Raj Patel",
    "specialty": "General Surgeon",
    "rating": "4.9",
    "distance": "1.8km Away",
  },
  {
    "image": "assets/images/male-doctor.png",
    "name": "Dr. Emily Brown",
    "specialty": "Endocrinologist",
    "rating": "4.6",
    "distance": "700m Away",
  },
  {
    "image": "assets/images/docto3.png",
    "name": "Dr. Michael Lee",
    "specialty": "Urologist",
    "rating": "4.7",
    "distance": "1.4km Away",
  },
  {
    "image": "assets/images/doctor2.png",
    "name": "Dr. Fatima Khan",
    "specialty": "Ophthalmologist",
    "rating": "4.8",
    "distance": "1.9km Away",
  },
  {
    "image": "assets/images/black-doctor.png",
    "name": "Dr. Carlos Ruiz",
    "specialty": "ENT Specialist",
    "rating": "4.5",
    "distance": "1.0km Away",
  },
  {
    "image": "assets/images/male-doctor.png",
    "name": "Dr. Olivia Chen",
    "specialty": "Rheumatologist",
    "rating": "4.7",
    "distance": "1.3km Away",
  },
];